---
title: "counts_update"
author: "bobby"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RODBC)
```

## Counts Updater  
This file contains scripts to automatically update counts data for LGS passage indicator. It also creates this document torecord the scheduled data update.

```{r counts-update}
# query FPC database to update the LMN and LGS counts ----
channel <- odbcDriverConnect("case=nochange;Description=Global;
  DRIVER=SQL Server;SERVER=SQL2;UID=sa;PWD=frznool;
  WSID=CUTTHROAT;DATABASE=pittag;Network=DBMSSOCN")

ad_ct <- sqlQuery(channel, "
SELECT dam, datadate, chin_adult, chin_jack, 'chin_all' = (chin_adult + chin_jack) 
from [pittag].[dbo].[HistFishTwo]
  where dam in ('LGS', 'LMN')
  and datepart(MM, datadate) in ('4','5','6')
  and datepart(YYYY,datadate) between '1991' and '2018'
  order by dam, datadate
")

odbcCloseAll()

# make lagged LMN counts variables and clean up for data updating ----
ad_ct$obsDate<- as.Date(ad_ct$datadate, format="%Y-%m-%d")
ad_ct$obsYear<- format(ad_ct$obsDate, "%Y")
ad_ct<- ad_ct[,-c(2:4)]

for(yr in unique(ad_ct$obsYear)){
  # lag LMN counts back 1
  lmn_dat<- subset(ad_ct, obsYear== yr & dam== "LMN")
  names(lmn_dat)<- c('dam', 'lmn_0', 'obs_date', 'obs_yr')
  lmn1<- cbind(obs_date=lmn_dat$obs_date+ 1, lmn_1=lmn_dat$lmn_0)
  lmn_dat<- merge(lmn_dat, lmn1, by= "obs_date")
  lmn_dat<- lmn_dat[,-c(2,4)]
  
  lgs_dat<-subset(ad_ct, obsYear== yr & dam== "LGS")
  names(lgs_dat)<- c('dam', 'lgs', 'obs_date', 'obs_yr')
  # Combine LGS data with LMN data using Lag date to merge
  if(yr=='1991'){
    ad_dat<- merge(lmn_dat, lgs_dat[,-1], by= 'obs_date')
  } else{
    temp<- merge(lmn_dat, lgs_dat[,-1], by= 'obs_date')
    ad_dat<- rbind(ad_dat, temp)
  }
}

# save new data to passage indicator data folder ----
wd<- "G:/STAFF/Bobby/adult passage/passage-indicator"
save(ad_dat, file=paste0(wd, '/da_indicator/data/ad_dat.Rdata'))
```

```{r pit-tags-update}
# query for pit-tagged spring Chinook (ihr to gra) ----
channel <- odbcDriverConnect("case=nochange;Description=Global;
  DRIVER=SQL Server;SERVER=PITTAG_SQL6;UID=sa;PWD=frznool;
  WSID=CUTTHROAT;DATABASE=PITGLOBAL;Network=DBMSSOCN")

xich <- sqlQuery(channel, "
  select a.tag_id, a.boa_obs, a.mca_obs, a.ich_obs, a.gra_obs,
    a.srrt, a.river_km, a.tag_site, a.capture_di, a.tag_date, a.rel_date,
  'mig_his' = case
  WHEN CHARINDEX('2', a.capture_di) = 0 THEN 'river'
  else 'trans'
  end
  
  from PITGLOBAL.dbo.[INTERROGATION BY SITE] a
  --where a.srrt IN ('11H', '11W', '12H', '12W') AND
  where substring(a.srrt, 1, 1) in ('1') and
  a.ich_obs is not null
  and datepart(mm, a.ich_obs) in ('4','5','6')
  --and a.migr_yr between '2003' and '2015'
  and datepart(yyyy, a.ich_obs) between '2005' and '2017'
  
  order by ich_obs, tag_id  
  ")
odbcCloseAll()

# flow data ----
channel <- odbcDriverConnect("case=nochange;Description=Global;
  DRIVER=SQL Server;SERVER=SQL2;UID=sa;PWD=frznool;
  WSID=CUTTHROAT;DATABASE=pittag;Network=DBMSSOCN")

flow2 <- sqlQuery(channel, "
SELECT site, date, AvgTotalDischarge, AvgTotalSpill, AvgTurbineDischarge, AvgUnitsOnLine, AvSpillPct = round(((AvgTotalSpill/AvgTotalDischarge) * 100),0)
  FROM [fpc].[dbo].[tbl_coe_mean_flow]
  where site in ('LGR', 'IHR')
  and datepart(MM, date) in ('4','5','6')
  and datepart(YYYY,date) between '1991' and '2018'
  order by site, date
  ")

odbcCloseAll()

flow2$date<- as.Date(flow2$date, format='%Y-%m-%d')
flow_ihr<- subset(flow2, site=='IHR')[,-1]
names(flow_ihr)<- c('obs_date', 'dis_ihr', 'spill_ihr', 'tur_ihr', 'unit_ihr', 'spct_ihr')
flow_lgr<- subset(flow2, site=='LGR')[,-1]
names(flow_lgr)<- c('obs_date', 'dis_lgr', 'spill_lgr', 'tur_lgr', 'unit_lgr', 'spct_lgr')
flow_dat<- merge(flow_ihr, flow_lgr, by= 'obs_date')

# temperature data ----
channel <- odbcDriverConnect("case=nochange;Description=Global;
  DRIVER=SQL Server;SERVER=SQL2;UID=sa;PWD=frznool;WSID=CUTTHROAT;
  DATABASE=fpc;Network=DBMSSOCN")

tdMost <- sqlQuery(channel, "
  SET NOCOUNT ON
  SET ANSI_WARNINGS OFF
  
  -- Clean data
  SELECT [date], [site],
  'temp_tdg' = CASE WHEN temp_tdg BETWEEN 0 AND 30 THEN temp_tdg ELSE NULL END,
  'tdgs' =    CASE WHEN tdgs BETWEEN 95 AND 140 THEN tdgs ELSE NULL END
  INTO ##temp              
  FROM [fpc].[dbo].[tdgs_hourly_historic]
  WHERE DATEPART(YYYY, [date]) BETWEEN 2005 AND 2013 AND
  --[site] in ('idsw','lmnw','lgsw','lgnw') 
  [site] = 'idsw' 
  
  -- Compute daily averages
  SELECT 'date' = CONVERT(date,[date]),
  [site],
  'temp'=AVG(temp_tdg),
  'tdgs'=AVG(tdgs)
  FROM ##temp
  WHERE DATEPART(YYYY, [date]) BETWEEN 2005 AND 2013
  GROUP BY [date], [site] ORDER BY [date]  
  
  DROP TABLE ##temp
  ")

# Aug 2013 and up
tdRest <- sqlQuery(channel, "
  SET NOCOUNT ON
  SET ANSI_WARNINGS OFF
  
  -- Clean data
  SELECT [date], [site],
  'degf' = CASE WHEN degf BETWEEN 32 AND 86  THEN (degf - 32)/1.8 ELSE NULL END,
  'tdgs' = CASE WHEN tdgs BETWEEN 95 AND 140 THEN tdgs            ELSE NULL END
  INTO ##temp              
  FROM [fpc].[dbo].[tdg_spill_archive]
  WHERE [date] >  '2013-08-31 00:00:00' AND
  --[site] in ('idsw','lmnw','lgsw','lgnw') 
  [site] = 'idsw' 
  
  SELECT 'date' = CONVERT(date,[date]),
  [site],
  'temp'=AVG(degf),
  'tdgs'=AVG(tdgs)
  FROM ##temp
  GROUP BY [date], [site] ORDER BY [date]  
  
  DROP TABLE ##temp
  ")

odbcCloseAll()

tdMost$date <- as.Date(tdMost$date)
tdRest$date <- as.Date(tdRest$date)

# Bring temper datasets together
# Avoid overlapping datasets
tdMost <- subset(tdMost, tdMost$date < min(tdRest$date))

# Stack 2 temperature datasets
td <- rbind(tdMost, tdRest)
td <- td[order(td$date),] 

# put NA for data in missing dates
# no matter if we only use april, may, and june
allDates <- seq(min(td$date), max(td$date), 1)
missingDates <- allDates[!allDates %in% td$date]
tmp <- data.frame(date=missingDates, site="IDSW", temp=NA, tdgs=NA)
td <- rbind(td, tmp)
td <- td[order(td$date),]
# all(diff(td$date) == 1) # Should be true
td$site<- 'IDSW'

# format pittag data and merge with flow and temper data ----
xich$obs_date<- as.Date(xich$ich_obs, format='%Y-%m-%d')
xich$yr<- format(xich$ich_obs, format='%Y')
xich<- subset(xich, (yr==format(boa_obs, format='%Y')|yr==format(mca_obs, format='%Y')) & obs_date-as.Date(rel_date, format='%Y-%m-%d')>365)
xich$jday<- as.numeric(format(xich$ich_obs, format='%j'))
xich$jday2<- as.numeric(format(xich$gra_obs, format='%j'))

pitflow2<- merge(xich, flow_dat, by= 'obs_date') # flow_dat from above
pitflow2$ftt<- with(pitflow2, gra_obs-ich_obs)
pitflow2$ftt<- as.numeric(pitflow2$ftt)
pitflow2<- subset(pitflow2, (ftt>0 & ftt<100)|is.na(ftt))
pitflow2<- pitflow2[substr(pitflow2$river_km, 1, 3)==522 & 
    substr(pitflow2$river_km, 5, 7)>=173,] # get rid of fish below lgr
pitflow2$flow<- ifelse(pitflow2$dis_ihr>100, '3high',
  ifelse(pitflow2$dis_ihr<60, '1low', '2med'))
kms2<- cbind(as.numeric(substr(pitflow2$river_km, 5,7)),
  as.numeric(substr(pitflow2$river_km, 9,11)),
  as.numeric(substr(pitflow2$river_km, 13,15)),
  as.numeric(substr(pitflow2$river_km, 17,19)),
  as.numeric(substr(pitflow2$river_km, 21,23)))
pitflow2$km<- rowSums(kms2, na.rm=TRUE)
pitflow2$tag_site<- trimws(pitflow2$tag_site)
# data exclude traps
pitflow2<- subset(pitflow2, !tag_site %in% c('CLWTRP','GRNTRP','IMNTRP','SNKTRP'))
# bring temper data (from above) in 
td_temp<- td[,c(1,3)]
names(td_temp)<- c('obs_date', 'ihr_temp')
pitflow2<- merge(pitflow2, td_temp, by= 'obs_date')

pitflow2$sjday<- scale(pitflow2$jday)
pitflow2$sdis_ihr<- scale(pitflow2$dis_ihr)
pitflow2$skm<- scale(pitflow2$km)
pitflow2$sihr_temp<- scale(pitflow2$ihr_temp)

# save new data to passage indicator data folder ----
wd<- "G:/STAFF/Bobby/adult passage/passage-indicator"
save(pitflow2, file=paste0(wd, '/da_indicator/data/pitflow2.Rdata'))
```


```{r app-update}
# deploy the shiny app again to update data
local({r <- getOption("repos")
       r["CRAN"] <- "https://ftp.osuosl.org/pub/cran/" 
       options(repos=r)
}) # set CRAN mirrow

rsconnect::deployApp(appDir = paste0(wd, '/da_indicator'),
  account="boppingshoe", appId = "281668",
  launch.browser = FALSE, forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
```


